# Generated by Django 2.1.7 on 2019-05-04 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=datetime.date(2019, 5, 4))),
                ('end_date', models.DateField(default=datetime.date(2019, 5, 5))),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
